### PR TITLE
fix non-passing tests for logging on pytest >= 3.3.0

### PR DESCRIPTION
**Pull request by camilojimenez**
This fixes issue #2550, where some tests fail when using newer pytest (after version 3.2.5).

The reason for this issue is that pytest added a plugin that instantiates a handler for the logging module, while the tests were expecting no handlers.

The PR solves the issue by temporarily disabling the logging module and removing any handlers for all tests on the file

### CODE REVIEW

**Comment by davidism** [comment]
Since it's also possible to disable the plug-in in other ways, it would be better to only restore it if it was actually enabled to begin with.

**Comment by davidism** [comment]
You can ignore the failures on 2.6 and 3.3.

**Comment by lepture** [comment]
@davidism are we going to remove the support for 2.6 and 3.3?

**Comment by ThiefMaster** [comment]
Yes

**Comment by davidism** [comment]
Yes. First step is removing the tests from CI, I just haven't gotten around to it for the other Pallets projects yet.

**Comment by camilojimenez** [comment]
@davidism done, now it only adds it back if it was set to begin with

**Comment by davidism** [comment]
Thanks for figuring this out. I did a bit of refactoring: use the `pytestconfig` fixture instead of accessing `pytest.config`, and `unregister` returns the plugin.

**Pull request merged**
