### PR TITLE
Add test for find_default_import_path

### PR DESCRIPTION
**Pull request by antsar**

### CODE REVIEW

**Comment by antsar** [comment]
Updated to properly cover the case where the environment variable is None.

**Comment by jeffwidman** [comment]
Looks like you accidentally pulled in 8b8df0cb7c1e4a2e01fe3e5f9f9ede651ef53b57 from upstream... You need to drop that, then rebase

**Comment by antsar** [comment]
I *thought* I saw that, but wasn't sure if I did it or it was some weird Github thing. Thanks for the heads up.

**Comment by davidism** [comment]
This is the one related to your pr: https://travis-ci.org/pallets/flask/jobs/135850955.  Can't reproduce the error locally.

**Comment by antsar** [comment]
Looks like it builds fine now though? ¯\_(ツ)_/¯

**Comment by untitaker** [comment]
Yes, see #1893

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
