### PR TITLE
[Minor changes] Update documentation by removing outdated information

### PR DESCRIPTION
**Pull request by bartbroere**
I noticed something about the market share of Internet Explorer and thought "that can't be true". After fixing that I also found out that Mark Pilgrim's book has been published, so I updated that as well.

### CODE REVIEW

**Comment by davidism** [comment]
Thanks. I'd rather not include the link to the book, we don't really include links to paid resources. This whole page should probably be removed, it doesn't seem particularly relevant anymore.

**Comment by bartbroere** [comment]
> Thanks. I'd rather not include the link to the book, we don't really include links to paid resources. This whole page should probably be removed, it doesn't seem particularly relevant anymore.

I agree that it seemed a bit outdated to me while reading it. Should I remove this pull request, or change it to omit the O'Reilly link?

**Comment by davidism** [comment]
You can either remove the link or remove the page, I'll merge either one.

**Comment by davidism** [comment]
Looks like there's some leftover trailing spaces, need to remove those to get the style test to pass.

**Comment by bartbroere** [comment]
Okay, I have removed the O'Reilly link. Thanks for the quick reply!

**Comment by bartbroere** [comment]
> Looks like there's some leftover trailing spaces, need to remove those to get the style test to pass. (Don't worry about the range test, that's expected to fail right now.)

I got them out of there (finally).

**Pull request merged**
