### PR TITLE
improve typing for `teardown_request` 

### LINKED ISSUE #4093: Wrong typing for teardown_request decorator
According to the [doc](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.teardown_request), the return values of teardown functions are ignored. However in `flask 2.0.1` the decorator only accept functions returning a `Response`.

It should accept to decorate functions returning any type.

Environment:

- Python version: 3.9
- Flask version: 2.0.1

### PR DESCRIPTION
**Pull request by pcorpet**
- fixes #4093

Checklist:

- [X] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [X] Run `pre-commit` hooks and fix any issues.
- [X] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by pgjones** [comment]
I think returning None might be more informative to end users. This way they'll be warned if they add a return expecting it to be used.

**Comment by pcorpet** [comment]
@pgjones yes, I prefer returning `None` as well. I didn't want to break the type of other code (especially for the ones that typed this file by setting `Response`), but I'll follow you gladly.

**Comment by hynek** [comment]
Maybe the changelog should be expanded? I've run into the same problem with `teardown_appcontext` and it seems like this PR fixes it for all `teardown_*` methods?

**Comment by pgjones** [comment]
Yep, minor change in 63893a427bd022d192febadad0b31ae06fa80776.

**Pull request merged**
