### PR TITLE
remove tests and docs for python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by davidism**
pallets/meta#24

I'll test 2.6 and 3.3 before I release 1.0, which will be the last version to support these.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Do we really want to include 2.6/3.3 in the 1.0 release?

**Comment by davidism** [comment]
I'm OK with removing them completely. When I said "1.0 will be the last version" I meant even for maintenance releases after that, so it's mostly just a last concession.

**Comment by davidism** [comment]
If you think it's OK, I'd rather just completely stop supporting 2.6 and 3.3 right now.

**Comment by ThiefMaster** [comment]
I'd do one last release before 1.0 and then drop it with 1.0

**Comment by davidism** [comment]
I'm not going to make a 0.13 release. The only thing blocking me from releasing 1.0 is finishing the tutorial. If we make a new release now, 1.0 will have nothing in it.

**Comment by ThiefMaster** [comment]
maybe the last release is fine for forever-yesterdays who still use 2.6 ;)

**Comment by davidism** [comment]
Yeah, I'm fine with that. That's basically what this would be, 1.0 just "secretly" still supports 2.6 if someone just happens to be able to upgrade Flask without upgrading Python.

**Comment by lepture** [comment]
I'm fine with that. If people want to use Python 2.6, they can still use the old version of Flask.

**Pull request merged**
