### PR TITLE
Issue #836: Tweaking tutorial warning about plain text passwords and …

### LINKED ISSUE #836: Tutorial stores passwords in plaintext
http://flask.pocoo.org/docs/tutorial/views/#login-and-logout

Flask should not lead new users astray, and should instead make it as easy and obvious as possible to do the right thing.

### PR DESCRIPTION
**Pull request by wldtyp**
…pointing users towards extensions registry

Not a huge change, but hopefully makes it clear that plain text is dangerous and puts people on the right path to implement password hashing if they choose

fix #836

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Can you please amend the commit message? Ideally the first line should be no longer than 51 chars; the current one is so long that even GitHub truncates it.

http://chris.beams.io/posts/git-commit/ has some good guidelines on writing nice commit message.

**Comment by wldtyp** [comment]
No problem. I've changed it to something better. Thanks!

**Comment by jeffwidman** [comment]
LGTM, @ThiefMaster anything I might have missed?

**Comment by ThiefMaster** [comment]
LGTM

**Comment by jeffwidman** [comment]
Thanks again @wldtyp for your help at the Pycon Sprint today!

**Pull request merged**
