### PR TITLE
Remove old version added and changed tags #1704

### PR DESCRIPTION
**Pull request by dawran6**
Removed the versionadded and versionchanged tags except for the one linked from external docs. Created issue #1852 to remove those tags from external docs.

### CODE REVIEW

**Comment by jeffwidman** [comment]
LGTM, squash and I'll merge

**Comment by untitaker** [comment]
Hang on, do we have any sort of consensus on what to do with those markers? Merging seems a bit too eager

**Comment by jeffwidman** [comment]
No problem, I'll hold off.

Over in #1704 both myself and @davidism were on board with doing this and no one objected, so I assumed we were good to go.

**Comment by ThiefMaster** [comment]
+1 for keeping them but making old ones look less important (or collapsing them). Removing them seems more like a good idea for a post-1.0 version once 1.0 is widespread and previous versions are considered obsolete and a bad idea to use

**Pull request closed without merging**
