### PR TITLE
Fix for #1740

### PR DESCRIPTION
**Pull request by JiriBalcar**
#1740

### CODE REVIEW

**Comment by JiriBalcar** [comment]
Added encoding to open_resource with default None so it is not breaking change

**Comment by davidism** [comment]
Use [`codecs.open`](https://docs.python.org/3/library/codecs.html#codecs.open) for compatibility with 2 and 3.    Needs documentation and a test would be nice too.

**Comment by davidism** [comment]
On second look, I can't figure out why this fails for you.  It's opening the file in binary mode, it shouldn't matter what the encoding is at that point.

**Comment by JiriBalcar** [comment]
if you will open the file in 'r' mode instead of 'rb' it will fail. For now, I changed the opening mode to 'rb' and decoding it myself. I will take a look on codecs.open and will try to update this pull request, because I think it will look better if the encoding can be defined in open_resource.

**Pull request closed without merging**
