### PR TITLE
Remove old version added and changed tags #1704

### PR DESCRIPTION
**Pull request by dawran6**
Remove "versionadded" and "versionchanged" tags < 0.10. Discussed in #1704.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Committing commented-out code is usually noise...

**Comment by dawran6** [comment]
I accidentally closed my first attempt while I was cleaning up my branches. (Sorry.) This PR is a duplicate of my first attempt, a.k.a. the delete-tags commit, instead what's described in the above comments.

**Comment by davidism** [comment]
I ended up writing a Sphinx extension to handle collapsing the changelog so we don't have to remove anything.

**Comment by Hogg123456789** [comment]
Misery

**Pull request closed without merging**
