### PR TITLE
Small SQL formatting fix in tutorial

### PR DESCRIPTION
**Pull request by Elahi-cs**
Found a small formatting slip while I was going through the tutorial, so I changed the line to be consistent with the rest of the SQL syntax.

### CODE REVIEW

**Comment by davidism** [comment]
Any change to the tutorial code needs to be changed in the corresponding example code as well.

**Comment by davidism** [comment]
As this is a docs change, please rebase to the 2.0.x branch.

**Comment by davidism** [comment]
Please squash the commits as well, after changing the base:

```
git rebase -i origin/main
git push -f
```

**Comment by Elahi-cs** [comment]
I'm not sure whether that did it, I'm pretty new at this and found what appeared to be a simple task surprisingly confusing. 

I apologize for the inconvenience and will gladly take any other instructions you have.

**Comment by davidism** [comment]
Yep, looks like you messed up the rebase. Just make a new PR against 2.0.x. Unfortunately using GitHub's editor usually causes more confusion than cloning and editing locally.

**Pull request closed without merging**
