### PR TITLE
Fix import order to accommodate pocoo style

### PR DESCRIPTION
**Pull request by pigletfly**
Fix some import order

### CODE REVIEW

**Comment by davidism** [comment]
Thank you, but we don't accept style PRs.

**Comment by pigletfly** [comment]
Some imports follow PEP 8 style , but some are not.I think there should be a coherent import style,PEP 8 style or [Pocoo Styleguide](http://flask.pocoo.org/docs/0.12/styleguide/#general-layout) style.

**Comment by davidism** [comment]
https://github.com/pallets/flask/pull/1702#issuecomment-294037694

**Comment by pigletfly** [comment]
got it

**Pull request closed without merging**
