### PR TITLE
switch to packaged sphinx theme

### PR DESCRIPTION
**Pull request by davidism**
I fixed up  flask-sphinx-themes so that it's an installable package. No longer need to copy files or use submodule, just `pip install Flask-Sphinx-Themes`.

### CODE REVIEW

**Comment by untitaker** [comment]
Similar effort at https://github.com/pallets/click/pull/402

**Comment by untitaker** [comment]
Also I think the flask docs builder doesn't even use that submodule repo but a different one.

**Comment by davidism** [comment]
Yeah, I know the docs builder is doing its own thing, but I'm with you on wanting to switch away from that.

The flask-sphinx-themes repo is the one linked as a submodule here and in various extensions.  People were submitting issues and patches to it.  It's also the one that was moved to the Pallets org.

I like your idea of having all the themes in one repo, just in case people want to document extensions for the other Pallets projects.  I'll go back and merge the two.

**Comment by kennethreitz** [comment]
Why not just move to Alabaster? It's more actively maintained and is based on the same codebase.

**Comment by untitaker** [comment]
You can close this, I'm not getting involved into the docs infra anymore. If
you want to propose the RTD theme you should discuss this with Armin, as it's
up to him in the end.

**Comment by untitaker** [comment]
Nvm about closing, I thought this was one of my PRs

**Comment by kennethreitz** [comment]
Related: https://github.com/pallets/flask/issues/2327

**Comment by kennethreitz** [comment]
https://github.com/pallets/flask/issues/2336

**Pull request merged**
