### PR TITLE
Comment out helpful tips in ISSUE_TEMPLATE so they're visible only when editing

### PR DESCRIPTION
**Pull request by aadibajpai**
The comments are now visible only to the issue creator and do not need to be manually removed before submitting the issue.

### CODE REVIEW

**Comment by jab** [comment]
Thank you for the contribution!

**Comment by aadibajpai** [comment]
Thanks for the framework in the first place!

**Comment by davidism** [comment]
Then again, I did that on purpose to make sure people were paying attention.

**Comment by aadibajpai** [comment]
> 
> 
> Then again, I did that on purpose to make sure people were paying attention.

Not sure it makes a difference, I found out I read it when it appears suddenly because it does not appear in the preview. That happened when opening this PR

**Comment by jab** [comment]
Sorry @davidism, want me to revert?

**Pull request merged**
