### PR TITLE
Update documentation for upgrading Flask using 'pip' command

### PR DESCRIPTION
**Pull request by ameya-pandilwar**
Fix for #1915

### CODE REVIEW

**Comment by jeffwidman** [comment]
Can you remove the `easy_install` instructions as well instead of just augmenting them? 

We'll get fewer support issues if we minimize the recommended install methods, and those who want to do things differently hopefully already know what they're doing.

**Comment by ameya-pandilwar** [comment]
@jeffwidman - added the `pip` commands and removed the `easy_install` instructions!

**Comment by jeffwidman** [comment]
Thanks!

**Comment by davidism** [comment]
Would you mind doing this for `installation.rst` as well?

**Comment by jeffwidman** [comment]
@davidism That's already handled over in #1920 although I'd appreciate if you'd be willing to review it.

**Pull request merged**
