### PR TITLE
give priority to '-e/--env-file' option over default files (#5628)

### PR DESCRIPTION
**Pull request by jalaj711**
This PR fixes issue #5628 . The issue arose from the fact that `FlaskGroup().make_context()` was loading the default env files before loading the arguments (by calling `super().make_context()`. Simply reversing the order of these actions fixes the issue. I have added the relevant tests to make sure it works.

- [x] Add tests that demonstrate the correct behavior of the change. Tests
  should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in CHANGES.rst summarizing the change and linking to the issue.
- [x] Add `.. versionchanged::` entries in any relevant code docs.

### CODE REVIEW

**Comment by jalaj711** [comment]
The failing test seems to be failing in other actions before this PR as well: https://github.com/pallets/flask/actions/runs/11709066697/job/32612272783

**Comment by davidism** [comment]
I don't think this is going to work. The env vars need to be loaded before creating the context, as the processing pipeline needs to be able to see the env vars to use their values for the parameters.

**Comment by davidism** [comment]
`override` is also not correct, as `os.environ` should still take precedence.

**Comment by jalaj711** [comment]
@davidism Thank you for your feedback, I have changed that approach. The tests are still passing as expected. Can you please take a look at this now?

**Comment by davidism** [comment]
I'm also already working on this using a different approach, sorry for the confusion.

**Comment by jalaj711** [comment]
Okay, I am kind of stuck at this point. Can you provide any ideas about how this might be implemented?

**Comment by davidism** [comment]
Closing in favor of #5630

**Pull request closed without merging**
