### PR TITLE
error on file upload document

### PR DESCRIPTION
**Pull request by red-alert**
In file upload example, after file uploaded, it should redirect to uploaded_file page instead of upload_file page.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Why does your PR contain a merge commit?

**Comment by red-alert** [comment]
I made a pull request to my fork, then I merged it before making a pull request to your repository

**Comment by davidism** [comment]
I needed to rebase this to 1.0-maintenance.

Your fork is probably going to be messed up after this, since you made the PR from your master and I'm force pushed it to look like 1.0-maintenance. You can probably fix it by fetching and force pushing origin/master and origin/1.0-maintenance to your fork once this is merged, or just delete and fork again.

In the future, it's always a good idea to make PRs from branches in order to avoid this.

**Comment by nitrocode** [comment]
I just ran into this same issue. Glad there's already a PR for it. Thank you @red-alert

**Pull request merged**
