### PR TITLE
Happy new year 2016

### PR DESCRIPTION
**Pull request by elahmo**
Quickly, before 2017 comes...

### CODE REVIEW

**Comment by davidism** [comment]
We are no longer changing copyright years each year. Copyright is established at the first moment a work is created, it does not need to be incremented.

**Comment by davidism** [comment]
If you would like to go the other direction and restore the original dates for all files with copyright statements, that would be appreciated, but it requires a bit of Git forensics.

**Comment by ThiefMaster** [comment]
Sounds a bit like overkill tbh. I'd rather just get rid of the dates altogether...

**Comment by davidism** [comment]
I have no strong opinion on it besides "don't need to update it."

**Pull request closed without merging**
