### PR TITLE
test_url_generation_with_parameter added

### PR DESCRIPTION
**Pull request by eso31**
I added a test for the url generation when a parameter is used.

### CODE REVIEW

**Comment by lepture** [comment]
Your commit is actually decreasing the test coverage since tests code are included in coverage. https://codecov.io/gh/pallets/flask/commit/ffe4acb667dfd78f28558d5eccbb38f7eabeec93

And a `route` should return something instead of `pass`.

**Comment by ThiefMaster** [comment]
I don't think the return value is relevant when just using it to generate URLs and not actually call it.

Anyway, you could register the route without a function and `build_only=True`.

**Comment by eso31** [comment]
Thank you for your comments, I tried to make a similar test with a different scenario and when I did the test coverage I didn't see that it actually decremented it. I also tried to register the route with build_only=True but I could test the url generation without the function.

**Comment by davidism** [comment]
Thanks for working on this. This test doesn't seem necessary. Other tests around this are testing the `url_for` function specifically, this one tests Werkzeug's builder, which has already been tested. Even fixing the unused function, this wouldn't increase coverage.

**Pull request closed without merging**
