### PR TITLE
Change docs to use f-strings

### PR DESCRIPTION
**Pull request by erfanio**
I noticed old printf style string formatting in quite a few places in the documentation.
When I cloned to fix the quick start guide, I noticed it was already changed to f-strings style formatting in quickstart so I changed the rest too.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
@VilhelmPrytz I don't think having Python3 syntax in docs is a problem

**Comment by VilhelmPrytz** [comment]
> @VilhelmPrytz I don't think having Python3 syntax in docs is a problem

No, I actually agree with you 😄 But I still think it's worth mentioning somewhere in the docs that the guides work for Python 3 only (to avoid confusion).

**Comment by erfanio** [comment]
> > @VilhelmPrytz I don't think having Python3 syntax in docs is a problem
> 
> No, I actually agree with you 😄 But I still think it's worth mentioning somewhere in the docs that the guides work for Python 3 only (to avoid confusion).

I totally agree and initially I was going to open an issue to discuss how to best approach this. But [getting started guide has already been changed to use f-string](https://github.com/pallets/flask/commit/413778afc19ce9f0cb484878d86375729c14faf4) so I thought someone has already made this decision.

**Comment by VilhelmPrytz** [comment]
> > > @VilhelmPrytz I don't think having Python3 syntax in docs is a problem
> > 
> > 
> > No, I actually agree with you smile But I still think it's worth mentioning somewhere in the docs that the guides work for Python 3 only (to avoid confusion).
> 
> I totally agree and initially I was going to open an issue to discuss how to best approach this. But [getting started guide has already been changed to use f-string](https://github.com/pallets/flask/commit/413778afc19ce9f0cb484878d86375729c14faf4) so I thought someone has already made this decision.

Alright, that's a good point. If the decision already has been made, so be it :smile:

**Pull request merged**
