### PR TITLE
Add a minimal Flask application

### PR DESCRIPTION
**Pull request by tianhanfangyan**
Describe what this patch does to fix the issue.

Link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
There's one in the README: https://github.com/pallets/flask#a-simple-example

And FWIW, usually there's no reason to have `app.run()` in your code nowadays since there's `flask run`.

**Comment by tianhanfangyan** [comment]
ok, thanks. i just make a test.

**Comment by ThiefMaster** [comment]
please do no submit PRs to real repos of other projects for testing purposes.

**Comment by tianhanfangyan** [comment]
ok

**Pull request closed without merging**
