### PR TITLE
Update testing.rst

### PR DESCRIPTION
**Pull request by teichopsia-**
Python 3.4.2

Fix TypeError: Type str doesn't support the buffer API

### CODE REVIEW

**Comment by teichopsia-** [comment]
Sorry, first time I create a pull request and am unfamiliar with the process.
Closing this one since pull request #1987 has additional changes and couldn't figure out how to add them to this one.

**Comment by nateprewitt** [comment]
Hey @teichopsia-, for future reference, you simply have to push new commits to the existing branch and the PR will update :)

**Comment by teichopsia-** [comment]
Thanks @nateprewitt. In short, basically what I did and just give a better explanation of the reasons? I'm not sure if the commit message was descriptive enough.

**Comment by nateprewitt** [comment]
@teichopsia- Sorry this fell out of my queue. You can use `git commit --amend` to amend the last commit message. You can also use [`git rebase`](https://git-scm.com/docs/git-rebase) to do more involved commit modifications. That way you won't need to open a second PR in the future. Cheers!

**Pull request closed without merging**
