### PR TITLE
Add nested blueprints

### PR DESCRIPTION
**Pull request by jdemilledt**
Rough implementation of nested blueprints. Open to suggestions.
Fixes #593

### CODE REVIEW

**Comment by davidism** [comment]
I'd need to see the entire test suite for blueprints passing on nested blueprints (and their parent's behavior) before merging something like this.

I'd really like to address #1091 first, which is only going to get more confusing with this. It's not clear how relative `url_for` behaves in the nested blueprint case. This doesn't appear to track the active blueprint for children, so `request.blueprint` will still only point one level deep.

**Comment by davidism** [comment]
How does this interact with `subdomain` and `url_defaults`?

This doesn't appear to register child handlers such as `before_request` with the app. I haven't run it, but it looks like it would just fail if a child had a `before_request` handler because `Blueprint` doesn't have the `before_request_funcs` attr. Same with other handlers.

**Comment by davidism** [comment]
I occasionally think about this in regards to #1548. From that perspective I think it makes more sense to extract all registration functions and attrs into a common class that both `Flask` and `Blueprint` inherit.

**Comment by jdemilledt** [comment]
Those are some very good points I did not think to test.

**Comment by davidism** [comment]
Thanks for looking into this! I'm going to close it for now because I think we need to find a more general solution. I definitely think Flask should have this eventually, so if you want to keep developing and contributing that would definitely be appreciated.

**Comment by jdemilledt** [comment]
If you ever want assistance, feel free to email me.

**Comment by harveyslash** [comment]
How does this handle `blueprint.before_request` ? 
Is that function called only for the parent blueprint or for all the blueprints that call `register_blueprint` with the parent blueprint ?

**Comment by therealadityashankar** [comment]
@davidism you might be able to modify an entire app into a blueprint (like the flask-docs or some open source flask based site) and use it as a test

**Pull request closed without merging**
