### PR TITLE
Docs: Add missing backslash

### PR DESCRIPTION
**Pull request by greyli**

### CODE REVIEW

**Comment by davidism** [comment]
Paths only have one backslash, you're confusing that with a Python string.

**Comment by greyli** [comment]
@davidism The backslashes added are used to escape the origin one.

Check [here](http://flask.pocoo.org/docs/dev/cli/#environment-variables-from-virtualenv).

**Comment by davidism** [comment]
OK, please explain why you're making a change like that in the future.

**Comment by greyli** [comment]
Okay, sorry about that.

**Pull request merged**
