### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by zkanda**
Minor spelling fix.

### CODE REVIEW

**Comment by untitaker** [comment]
No, this is past-tense.

**Comment by zkanda** [comment]
Ahh didn't really understand that. Thanks for clarifying it @untitaker :+1:

**Comment by davidism** [comment]
Technically either is correct here, although I'd probably change it to "complicates" since the change happened in the past but the effect is continuous.  The rest of the paragraph is present tense as well.  Of course, now I'm questioning the choice of *affect* and *effect*.  :-/

**Comment by untitaker** [comment]
Agreed:

* complicate -> complicates
* affect -> effect

**Comment by davidism** [comment]
http://chat.stackoverflow.com/transcript/message/30984060#30984060 Consensus seems to be "affect" in both places.

**Comment by untitaker** [comment]
Yes, a typo of mine. Fixing both now.

**Comment by untitaker** [comment]
Fixed!

**Pull request closed without merging**
