### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by BTaskaya**
Fixed Typo in the tutorials
Changed when -> how

### CODE REVIEW

**Comment by hesapadim** [comment]
Isn't it correct already?
And, you misspelled _tutorials_ :P

**Comment by BTaskaya** [comment]
No, i am not misspelled. I think there is a problem related to your eyes.

**Comment by hesapadim** [comment]
I didn't misspell*
or
I haven't misspelled*

**Comment by yasngleer** [comment]
My English not perfect but I think how looks better

**Comment by BTaskaya** [comment]
I wrote "I didn't misspell" and i think you are just trolling me.  Please stop it!

**Comment by hesapadim** [comment]
"edited"

Anyways, it's not about how it looks better, it's about what's meant to say, right?

**Comment by BTaskaya** [comment]
I edited to adding something.

**Comment by ThiefMaster** [comment]
Stop this dumb nitpicking war right now, thanks.

**Comment by hesapadim** [comment]
to add*

In case if you edit it again.
image


@ThiefMaster yeah, if this guy could stop trolling, that'd be great. What do you think about this PR?

**Pull request closed without merging**
