### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by thetronjohnson**
Added how to enter debug mode

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Thanks, but I don't think this belongs in the README file

**Comment by thetronjohnson** [comment]
Okay I just felt the need that it should be...nevermind

**Comment by ThiefMaster** [comment]
It's here: http://flask.pocoo.org/docs/1.0/quickstart/#debug-mode

The README is really just show a very simple example on how a Flask app works.

**Comment by thetronjohnson** [comment]
okay

**Pull request closed without merging**
