### PR TITLE
Added a property is_body_json

### PR DESCRIPTION
**Pull request by smitthakkar96**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
What's the advantage of this? `request.get_json()` should cover all you need.

**Comment by smitthakkar96** [comment]
@ThiefMaster I think we need a property that validates the json of body as empty body with headers application/json results into 400.

**Comment by ThiefMaster** [comment]
You can catch the exception or use `silent=True`

**Comment by smitthakkar96** [comment]
I didn't notice silent parameter, btw thanks.

**Pull request closed without merging**
