### PR TITLE
PyCharm Run Configuration Guide

### PR DESCRIPTION
**Pull request by doobeh**
A guide showing how to get the `flask run` cli functionality directly within PyCharm-- addresses issue #2198. Even when PyCharm implements smoother integration, we're probably still going to need a variation of this to address factories/etc.

### CODE REVIEW

**Comment by pletnes** [comment]
Not sure if this is the appropriate place to put this, but following these instructions on Windows 10, except putting `flask.exe` in place of just `flask`, yields this gibberish error message:

```
Traceback (most recent call last):
  File "C:\Users\paul\Anaconda3\envs\sludd\lib\tokenize.py", line 390, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.4\helpers\pydev\pydev_run_in_console.py", line 78, in <module>
    globals = run_file(file, None, None)
  File "C:\Program Files\JetBrains\PyCharm 2017.1.4\helpers\pydev\pydev_run_in_console.py", line 35, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 11, in execfile
    stream = tokenize.open(file)  # @UndefinedVariable
  File "C:\Users\paul\Anaconda3\envs\sludd\lib\tokenize.py", line 454, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\paul\Anaconda3\envs\sludd\lib\tokenize.py", line 431, in detect_encoding
    encoding = find_cookie(first)
  File "C:\Users\paul\Anaconda3\envs\sludd\lib\tokenize.py", line 395, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:/Users/paul/Anaconda3/envs/sludd/Scripts/flask.exe'
```

**Comment by ThiefMaster** [comment]
This sounds more like pycharm tried to execute/debug flask.exe as a python file (which obviously can't work)...

**Comment by pletnes** [comment]
Yeah, that is true, but it's what the instructions suggest. That is, I guess `flask` is an actual python script on non-windows OS-es.

**Comment by pletnes** [comment]
OK, after some fiddling, I found that `flask-script.py` resides next to `flask.exe` and can be used in its place. This could be noted in an update to these docs.

**Comment by ThiefMaster** [comment]
Yes, on Windows Python wraps CLI scripts in a .exe. Try using `-m flask` as the args instead (`flask` / `flask.exe` is equivalent to `python -m flask`)

**Comment by pletnes** [comment]
Tried the `-m flask` trick already, that causes other issues with pycharm (would probably work in many other IDEs though)

**Comment by Nadav-Eyesight** [comment]
Windows user here, no `flask-script.py` found.
I finally managed to get it to work using `flask` as a module name and `run` as a parameter.

**Pull request merged**
