### PR TITLE
Fix Request Reference

### PR DESCRIPTION
**Pull request by barracks510**
Points flask.Request to appropriate place in the documentation.

### CODE REVIEW

**Comment by jeffwidman** [comment]
I'm actually a little confused... the current docs link to something called `class flask.request` which is listed under the proper `class flask.Request`... why do the docs distinguish the `request` object as it's a class? Is that correct or should it be changed?

**Comment by untitaker** [comment]
@jeffwidman `Request` is a class, `request` is the current instance of it.

**Comment by untitaker** [comment]
@barracks510 if this is not showing right in the docs I'm happy to learn about improvements, but there's a clear difference between those two paths. hence I'd tend to close this

**Comment by ThiefMaster** [comment]
IMO at least the changes on the tilde links make sense - so e.g. a mention to `method` points to the `Request.method` documentation. Since only the last segment is displayed it would only change (or rather add, currently there is no link) the link target

**Comment by untitaker** [comment]
Ah yes, I oversaw that.

**Comment by untitaker** [comment]
Thanks @barracks510!

**Comment by jeffwidman** [comment]
> Request is a class, request is the current instance of it.

Right, so why is the word ["class" located next to the `request` object](http://flask.pocoo.org/docs/0.12/api/#flask.request)? 
It visually makes it seem like it's a separate class from `Request`...

**Comment by untitaker** [comment]
That's an entirely valid complaint, I guess `attr` would be more appropriate.

**Pull request merged**
