### PR TITLE
Deprecate flask.ext

### PR DESCRIPTION
**Pull request by untitaker**
See #1135

### CODE REVIEW

**Comment by untitaker** [comment]
cc @DasIch (now on the PR properly)

**Comment by ThiefMaster** [comment]
Would it make sense to show a different warning in case a flask.ext import points to an old `flaskext` package?

**Comment by untitaker** [comment]
@ThiefMaster fixed, an additional warning is now shown. One is addressing the app dev, the other the extension dev.

**Comment by davidism** [comment]
What are we waiting on to merge this?

**Comment by untitaker** [comment]
Feel free to do so.

On 31 October 2015 05:02:17 CET, David Lord <notifications@github.com> wrote:
>What are we waiting on to merge this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/flask/pull/1484#issuecomment-152690731

-- 
Sent from my phone. Please excuse my brevity.

**Comment by jeffwidman** [comment]
Can someone rebase and then merge this?

**Comment by mitsuhiko** [comment]
Let's merge this.

**Pull request merged**
