### PR TITLE
Handle breaking changes of Werkzeug v1.0.0

### PR DESCRIPTION
**Pull request by ShubhankarS**
Describe what this patch does to fix the issue.
This fixes crash caused by v1.0.0 released by Werkzeug
Link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by ShubhankarS** [comment]
Sample error stack trace:
`File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/_compat.py", line 33, in reraise
     raise value
   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
     rv = self.dispatch_request()
   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/opt/python/current/app/application.py", line 1632, in health
     return jsonify({'status': 'success'})
   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/flask/json.py", line 251, in jsonify
     if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
   File "/opt/python/run/venv/local/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
     return getattr(self._get_current_object(), name)
 AttributeError: 'Request' object has no attribute 'is_xhr'`

**Comment by ShubhankarS** [comment]
This started breaking on our production servers and had to add an older version of `Werkzeug` to the projects `requirement.txt` to fix it

**Comment by pgjones** [comment]
@ShubhankarS the issue here (usage of `is_xhr`) has already been fixed in Flask - I think the version of Flask you are using is 0.12.X, whereas 1.0 onwards fixes this.

**Comment by gricey432** [comment]
I had the same problem using Flask 0.12.2 which has a dependency on `Werkzeug (>=0.7)`. So it just started picking up the break.

**Pull request closed without merging**
