### PR TITLE
grammar mistake fix

### PR DESCRIPTION
**Pull request by miquelvir**
Grammar mistake in comment from the fileuploads patterns example in the docs.

### CODE REVIEW

**Comment by davidism** [comment]
There are still grammatical issues with this. If fixing a top is important, please clean up the entire area.

**Comment by miquelvir** [comment]
Hi @davidism , it is my first PR and I am not a native English speaker. I have tried correcting all the mistakes in the file, but please let me know if I have done something wrong.

**Comment by davidism** [comment]
Sorry, I guess I wasn't clear. I was referring to the specific sentence you were editing, not the entire document.

**Comment by davidism** [comment]
Note that the original fix wasn't particularly necessary either.

> # if user does not select file, browser also
> # submit an empty part without filename

This sort of style, without the "a" and "the" before nouns, is common in code comments. The only thing wrong here is "browser also submit" should be "browser also submits".

**Comment by miquelvir** [comment]
Thank's for the clarification. It was not my original intention to change the 'the'; I only wanted to add the missing present simple 's', but was told to also add the 'the' before user: https://github.com/pallets/flask/issues/3768.

**Pull request merged**
