### PR TITLE
Number of characters in lines

### PR DESCRIPTION
**Pull request by Tzinapapadopoulou**
<!--
In some .py files, we noticed that the lines of code were exceeding the 79 characters per line rule, that is compatible with the PEP8 construction standard style. 
--

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [ ] Run `pre-commit` hooks and fix any issues.
- [ ] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
No thanks.

**Comment by davidism** [comment]
Also, we told you not to do this on Discord, why did you do it anyway?

**Comment by Tzinapapadopoulou** [comment]
I am so sorry, i just checked Discord, it looks like another classmate wanted to do the same as it is for a project. I knew that it is not a significant change and i did not want to annoy and waste your time. I am still a beginner.

**Comment by davidism** [comment]
Please provide this feedback to your teacher: stop doing this assignment, it's noisy and not helpful to maintainers. Pretty much every maintainer out there, especially for large projects, is already aware of tools like flake8, and either already runs them (we run linters and formatters, but both of you failed to check first) or doesn't want to. A random person coming by and making style changes everywhere is impossible to trust or review.

**Comment by Tzinapapadopoulou** [comment]
Yes got it. Can you delete this pr please? sorry again

**Comment by davidism** [comment]
PRs cannot be deleted.

**Pull request closed without merging**
