### PR TITLE
Add `--debug` option to flask run

### LINKED ISSUE #4777: CLI flask run describes that uses --debug to enable debugger and reloader, but flask run does not have the -- debug option
flask run --help description:   The reloader and debugger are enabled by default with the '--debug' option.
But when I use flask run --debug, it tells me that there is no --debug option

flask run --debug

image

According to the description of flask run --help, the --debug option should be supported.

Environment:

- Python version: 3.10.6
- Flask version: 2.2.2

### PR DESCRIPTION
**Pull request by greyli**
The alternative of #4778, fixes #4777

Using `flask run` with `--debug` is common usage, and adding this option to `flask run` makes the command more intuitive:

```
flask run --debug
```

If this change is accepted, then I will update the docs and add tests.

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [ ] Run `pre-commit` hooks and fix any issues.
- [ ] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by davidism** [comment]
It's a bit confusing to have both `--debug` and `--debugger` flags, but I'm guessing most people don't know about the second flag anyway. This mostly matches the signature for `app.run`, which calls them `debug` and `use_debugger`.

**Comment by greyli** [comment]
Rebased to 2.2.x and updated docs. I'm not sure if we need to add tests here, I was thinking something like this:

```py
@pytest.mark.parametrize(
    "option,value",
    (
        (["--debug"], True),
        (["--no-debug"], False),
    )
)
def test_run_debug(option, value):
    ctx = run_command.make_context("run", option)
    assert ctx.params["debug"] == value
```

But it seems unnecessary.

**Comment by greyli** [comment]
> It's a bit confusing to have both `--debug` and `--debugger` flags, but I'm guessing most people don't know about the second flag anyway. This mostly matches the signature for `app.run`, which calls them `debug` and `use_debugger`.

When this option was added, I think most people will use `--debug` over `--reload` and `--debugger`.

BTW, `--reloader` matches `--debugger` and `use_reloader` better. Do you think we need to rename `--reload` to `--reloader`?

**Comment by davidism** [comment]
I agree we should change `reload` to `reloader` as well, but I want to wait until Click can show a deprecation message for individual options.

**Pull request merged**
