### PR TITLE
Improve test coverage of flask.json

### PR DESCRIPTION
**Pull request by nland**
- Added tests for `flask.json.dump()` and `flask.json.load()`.
- Added a test to ensure that UUIDs are correctly jsonified.

### CODE REVIEW

**Comment by nland** [comment]
adjusting these tests to use a pytest tempfile instead of a real file object

**Comment by davidism** [comment]
You don't even need a tempfile, just a file-like object.

~~~python
from flask._compat import StringIO
out = StringIO()
flask.json.dump({'spam': 'eggs'}, out)
out.seek(0)
data = flask.json.load(out)
~~~

**Comment by jeffwidman** [comment]
@nland Curious why you closed this? 

Once you update the code, a simple `git commit --amend` followed by `git push -f` will push the updated code to this PR.

We'd certainly appreciate having the extra test coverage.

**Comment by untitaker** [comment]
Closing due to inactivity, please refile if updated.

**Comment by davidism** [comment]
rebased and pushed f16e477b2a7329d249b5793a0dc4986503a48371, cleaned up in f193f590bc33bde70fad200782350beac3506585

**Pull request closed without merging**
