### PR TITLE
Adds simplejson as a testing target.

### PR DESCRIPTION
**Pull request by JamesTFarrington**
Adds one test specifically for a simplejson bug.

### CODE REVIEW

**Comment by untitaker** [comment]
This does not test simplejson within travis! It only adds a tox env.

**Comment by untitaker** [comment]
Also adding this as an alternative value to "devel", "release" is wrong.

**Comment by jeffwidman** [comment]
My mistake, I'm going to hold off on merging any more code changes during this sprint then, as I'm clearly not doing a good job on reviewing right now.

**Comment by davidism** [comment]
We need to test both with and without `simplejson`, since both are supported right now.  If we added those two options on top of the others, we'd now be running 30 envs with `tox`.  That seems a bit excessive.

**Comment by davidism** [comment]
Travis has an example in the docs with 56 envs, I don't feel too bad about this now.

**Comment by untitaker** [comment]
@jeffwidman My suggestion would be to have a policy to require two maintainers to sign off; https://github.com/pallets/meta/issues/18

**Pull request merged**
