### PR TITLE
Correctly JSON-encode datetimes aware of non-UTC timezones

### LINKED ISSUE #2372: JSONEncoder encodes aware datetime objects in non-UTC timezone incorrectly as being in GMT.
``flask.json.JSONEncoder()`` encodes aware datetime objects in non-UTC timezone incorrectly using local time tuple with GMT.

### Expected Behavior

The following code segment should print ``"Sun, 01 Jan 2017 20:34:56 GMT"``  (12:34:56 PST8PDT is 20:34:56 GMT):

```python
from datetime import datetime
from pytz import timezone
dt = timezone('PST8PDT').localize(datetime(2017, 1, 1, 12, 34, 56))

from flask.json import JSONEncoder
encoder = JSONEncoder()
print(encoder.encode(dt))
```

### Actual Behavior

The preceding code segment prints ``"Sun, 01 Jan 2017 12:34:56 GMT"`` instead, that is, local timetuple() appended with GMT.

### Environment

* Python version: 3.5.3
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

### PR DESCRIPTION
**Pull request by astralblue**
http_date() requires timetuple in UTC, but JSONEncoder.default() was
passing a local timetuple instead.

This fixes #2372.

### CODE REVIEW

**Comment by davidism** [comment]
Thanks! Nice use of parametrize in the test.

Is it possible to test timezones without depending on pytz?

**Comment by astralblue** [comment]
`datetime.tzinfo` should theoretically be usable for simple cases (as we do not need DST logic of pytz to test JSONEncoder).  Will look into that.

**Comment by astralblue** [comment]
The new method fails because datetime.timezone is Python 3 only.  x_x  The only alternative would be to hand-spin a timezone class, which I feel is an overkill.  x_x

**Comment by davidism** [comment]
I'm fine with a test dependency on pytz then.

**Comment by davidism** [comment]
Be sure to add the dependency to the extra requirements in `setup.py` as well as `tox.ini`.

**Comment by davidism** [comment]
I take it back, that would mean a simple call to `pytest` would fail unless we made the test optional.

**Comment by astralblue** [comment]
Oops, I missed the edit to your comment and misunderstood.  Will revert these changes.

**Comment by davidism** [comment]
😓 sorry for the confusion

**Comment by zsiegel92** [comment]
Hey all, Flask 0.12.2 was released in May, so this can't be part of that. Will this be part of 0.13? For now, I will send timezone info separately.

Thank you!!

**Comment by davidism** [comment]
Jinja releases aren't tied to Flask releases.

**Comment by davidism** [comment]
This will be part of the next release.

**Comment by spacemunkey77** [comment]
Using  Flask 0.13-dev and jsonify() is still setting times in UTC. I have set the local time zone using the following code snippet:

    tz = TimezoneFinder()
    ltz = tz.timezone_at(lng=longitude, lat=latitude)
    os.environ['TZ'] = ltz
    time.tzset()

**Pull request merged**
