### PR TITLE
Continue #1489: Add kwarg to disable auto OPTIONS on add_url_rule 

### PR DESCRIPTION
**Pull request by davidism**
Merge master into #1489 and do some cleanup.

### CODE REVIEW

**Comment by untitaker** [comment]
I'm really curious why the original option was implemented as attribute on the
view function. Perhaps there is a reason it is not part of `add_url_rule`'s
signature.

**Comment by davidism** [comment]
Yeah, I found that a little weird too, but this doesn't seem to hurt anything.

**Comment by untitaker** [comment]
cc @mitsuhiko?

**Comment by davidism** [comment]
The original issue #1488 explains a little more: they're registering more routes by endpoint name, without providing the view function each time. So they can't set the attribute because there's nothing to set it on.

**Comment by untitaker** [comment]
That's fair, though I wonder if we should deprecate the other way to do it.

**Comment by davidism** [comment]
I'll open an issue separate from this.

**Pull request merged**
