### PR TITLE
fix type hint for `cli_runner.invoke`

### PR DESCRIPTION
**Pull request by kurtatter**
https://github.com/pallets/flask/issues/5645

Hello! I love Flask! This is my first attempt to start participating in open source, so I'm very nervous, even though the changes I've made are insignificant. Thank you!

From `testing.invoke() -> t.Any` to `testing.invoke() -> Result`

### CODE REVIEW

**Comment by davidism** [comment]
It looks like you committed as a different user than you posted as. Do you want to fix that?

**Comment by kurtatter** [comment]
yes

**Comment by davidism** [comment]
You can do the following:

```
$ git commit --amend --author 'Your Name <your email>' --no-edit
$ git push -f
```

**Comment by kurtatter** [comment]
Thanks a ton

**Comment by davidism** [comment]
Looks like that didn't work. Maybe you need to fix your git config locally and try again?

**Comment by kurtatter** [comment]
(˶ᵔ ᵕ ᵔ˶)

**Pull request merged**
