### PR TITLE
`static_folder` can be a `pathlib.Path` object

### LINKED ISSUE #4150: static_folder shows str type, not pathlib.Path
Using Python 3.9, mypy will complain about static_folder being `Optional[str]` and not accepting a `pathlib.Path`.

```
note: Revealed type is "pathlib.Path*" # This is what I'm feeding it
Revealed type is "Union[builtins.str, None]" # this is reveal_path() for app.static_folder
error: Incompatible types in assignment (expression has type "Path", variable has type "Optional[str]")
Found 1 error in 1 file (checked 1 source file)
```

Not sure why Python 3.8 doesn't do this.

I think maybe here: https://github.com/pallets/flask/blob/main/src/flask/scaffold.py#L80

I think this needs to be `_static_folder: t.Union[t.Optional[str], Path] = None`

Or maybe... `_static_folder: t.Optional[t.Union[str, Path]] = None`

And at the top: `from pathlib import Path`

Thank you!

### PR DESCRIPTION
**Pull request by Yourun-proger**
- fixes #4150 

Checklist:
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [x] Add .. versionchanged:: entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by pgjones** [comment]
This doesn't fix the issue - the typing needs to be extended to the static_folder arguments and then support for Path needs to be added where the static_folder is used.

**Comment by davidism** [comment]
Also need to use `os.PathLike` when typing.

**Comment by Yourun-proger** [comment]
@davidism, I want to clarify. That is, instead of `pathlib.Path`, you need to use `os.PathLike`  both in the static_folder and in the _ static_folder **too**?

**Comment by Yourun-proger** [comment]
Hello. I understood your adjustments and fix!

**Comment by i3Cheese** [comment]
`value = os.fspath(value).rstrip(r"\/")` returns `str`, so `static_folder` always return str, but can be set to `os.PathLike`

**Comment by Yourun-proger** [comment]
Hey! Do my changes still need any adjustments?

**Comment by i3Cheese** [comment]
Think 81 should be original  `_static_folder: t.Optional[str] = None`

**Comment by Yourun-proger** [comment]
Okay. I'll squash those 3 commits, then fix line 81. Thanks!

**Comment by Yourun-proger** [comment]
Okay. Now I seem to have done everything)
Or do you need something else?

**Comment by Yourun-proger** [comment]
Hey, @davidism , is everything right now?

**Comment by greyli** [comment]
You don't need to ask for reviewing or merging, please be patient. By the way, using "I fix it!" as the commit summary is not a good idea, and the current commit description is also meaningless.

**Comment by Yourun-proger** [comment]
Sorry! I am silent... I changed the commit message.

**Comment by Yourun-proger** [comment]
I found [this](https://github.com/pallets/flask/blob/7a73171edc3bcffef96ef6367977ab3ae9af9350/src/flask/app.py#L392) line of code and I suspect that it needs to be fixed too. But I'm not sure

**Comment by Yourun-proger** [comment]
Okay. All is good!

**Comment by Yourun-proger** [comment]
In Blueprint class i see `static_folder` too and i'll fix it tomorrow

**Comment by Yourun-proger** [comment]
Okay. I changed this. But i don’t really know where exactly to add `.. versionchanged :: 2.0.2` in Flask and Blueprint classes. Can anyone please help? Or say about some other necessary changes. Thank you!

**Pull request merged**
