### PR TITLE
Add last_modified arg for send_file

### PR DESCRIPTION
**Pull request by prachikhadke**
Enhancement: Add last_modified arg of type DateTime to send_file.

Fixes pallets/flask#1321

### CODE REVIEW

**Comment by jeffwidman** [comment]
@prachikhadke I think should be closed based on https://github.com/pallets/flask/issues/1321#issuecomment-223442890, correct?

**Comment by prachikhadke** [comment]
Yes. Can be closed.

**Comment by jeffwidman** [comment]
I'm going to re-open this until https://github.com/pallets/flask/issues/1321#issuecomment-223740840 is decided

**Comment by davidism** [comment]
af515cc7ea561292b07195c6a93662b7ca189e21, with some cleanup in 7c271401b284e6fcc2040fffe317342e2a17a902

**Pull request closed without merging**
