### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by davidism**

### CODE REVIEW

**Comment by davidism** [comment]
Docs are expected to fail until https://github.com/sphinx-doc/sphinx/issues/9216 is addressed.

**Comment by belmarca** [comment]
Congrats!

**Comment by mikhael28** [comment]
No description provided?! Congratulations! When I first started programming, the first http server I ever ran was on Flask. It was magical seeing that 'Hello world' pop up on the root route.

**Comment by davidism** [comment]
I was already writing enough announcements. :smile: You can find a lengthier announcement in the GitHub release page: https://github.com/pallets/flask/releases/tag/2.0.0, which links to our announcement blog: https://palletsprojects.com/blog/flask-2-0-released/ and tweet: https://twitter.com/PalletsTeam/status/1392266507296514048.

**Pull request merged**
