### PR TITLE
Remove outdated Pycharm instructions

### PR DESCRIPTION
**Pull request by jeffwidman**
This was originally added before Pycharm natively supported this.

Pycharm 2018.1 fixed that issue.

So these instructions are now more than two years out of date so they
are a potential source of confusion rather than helpful for n00bs.

Further context:
* https://github.com/pallets/flask/issues/2198
* https://github.com/pallets/flask/pull/2332
* https://youtrack.jetbrains.com/issue/PY-23190

### CODE REVIEW

**Comment by davidism** [comment]
I think the Flask run configuration is only available in PyCharm Professional, so these might still be relevant for Community users. Instructions might need to be updated though.

**Comment by jeffwidman** [comment]
Ah, good thought. I searched a bit but didn't find anything on Jetbrains site stating suppport was/wasn't included... I am not a Pycharm user myself, and the install is pretty heavy-weight so perhaps someone else who already has pycharm CE installed could chime in? If this doesn't get traction in a week I'll try to circle back and test it myself.

**Comment by RemiDesgrange** [comment]
There is no Flask run config in pycharm community. So you could say "Pycharm CE integration" ?

**Comment by davidism** [comment]
Updated the docs to mention PyCharm Professional vs. Community Edition: c6a619af

**Comment by jeffwidman** [comment]
Thanks for handling this!

**Pull request closed without merging**
