### PR TITLE
simplify and modernize some stuff for the tutorial project

### PR DESCRIPTION
**Pull request by Laurentiu-Andronache**
Describe what this patch does to fix the issue.

Link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
why are you removing the single quotes? they work everywhere and the chance that developers use a decent shell (ie zsh) is rather high...

**Comment by Laurentiu-Andronache** [comment]
@ThiefMaster, for example they give an error in Windows. The test stuff ain't getting installed. And they're not needed in bash, which gets more usage than zsh.

**Comment by ThiefMaster** [comment]
They may not be needed in bash, but they work fine there. And while bash is the default shell everywhere and thus the most commonly installed one, I don't think that's necessarily the case when counting only developer systems.

Maybe double quotes work on windows as well? In any case, Windows is probably the least common OS for web development out there...

**Comment by Laurentiu-Andronache** [comment]
Ok Maybe don't merge that commit then. Do you like the others though?

**Comment by davidism** [comment]
Thanks for looking at this. However, I don't think any of these changes are necessary or better, just different. Going to close this for now.

**Comment by Laurentiu-Andronache** [comment]
OK. But in the HTML code (and in the CSS as well), there's a lot of poor code (like multiple <h1> tags on the same page), non-responsive on mobile, etc. I'll submit a pull request tomorrow, and maybe you reconsider the commits that I did here as well when the time comes.

**Comment by davidism** [comment]
We don't control the HTML or CSS (for the most part), that's rendered by Sphinx. Multiple H1 tags are not poor code, the HTML5 outline algorithm has allowed that for almost a decade.

**Pull request closed without merging**
