### PR TITLE
Fix non-working  setup.cfg in tutorial docs with working copy from sa…

### PR DESCRIPTION
**Pull request by mitchjacksontech**
I worked through the tutorial today, but ended up with code that wouldn't run.
The provided example code in the repo does run.  
This pull matches the code in the docs to the example code

### CODE REVIEW

**Comment by davidism** [comment]
An alias so that `test` runs `pytest` is valid.

**Comment by mitchjacksontech** [comment]
valid yet not working

**Comment by untitaker** [comment]
What do you mean with "not working". What exactly crashes?

**Comment by davidism** [comment]
The change you made is invalid, no matter what behaviour you may be seeing. `test=pytest` is not a `pytest` config value. You'll need to describe the issue you're having in order for us to understand the problem.

**Comment by mitchjacksontech** [comment]
My apologizes, I must have misunderstood what I saw... I'll work through it from scratch and come back with full details.

**Pull request closed without merging**
