### PR TITLE
shell autocomplete

### LINKED ISSUE #3941: Add auto-completion to shell command
in often times we use the shell command to debug or ensure something, but there's a small problem which is we don't have auto-complete when we press the tab.
so I decided to make a pull request to add this feature.

The auto-complete it's very helpful to speed our development.

### PR DESCRIPTION
**Pull request by awbx**
in often times we use the shell command to debug or ensure something, but there's a small problem which is we don't have auto-complete when we press the tab.
so I decided to make a pull request to add this feature

- fixes #3941

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by davidism** [comment]
Readline isn't guaranteed to be installed, so you need to account for that.

**Comment by awbx** [comment]
I think the readline it's a built-in module?

**Comment by davidism** [comment]
Yes, but it's only available on some platforms, and depends on how Python was compiled.

**Comment by awbx** [comment]
I wish you add this feature if possible, it's very helpful in our development env.
Regards, Abdelhadi

**Comment by davidism** [comment]
Ok, but you need to address the comment I made. Paying that your want me to merge it isn't really helpful on its own.

**Comment by awbx** [comment]
@davidism, I'm not talking to merge my own, but wish if you add this feature, it's very helpful.

**Pull request closed without merging**
