### PR TITLE
Added a missing module to import statement

### PR DESCRIPTION
**Pull request by vioan**

### CODE REVIEW

**Comment by davidism** [comment]
`after_this_request` was written a couple sections up the page, it's not an import.

**Comment by vioan** [comment]
then perhaps the function should be added to the example as well? Because if somebody is just trying to copy/paste the example code, will not work as it is right now.

**Comment by ThiefMaster** [comment]
@davidism Actually, it is an import.

**Comment by vioan** [comment]
of course it is an import

**Comment by untitaker** [comment]
Reopening as a reminder, but the section needs a larger rewrite to make use of Flask's own version.

**Pull request merged**
