### PR TITLE
extending FlaskClient can override follow_redirects

### LINKED ISSUE #3396: Unable to extend FlaskClient with follow_redirects
I'm trying to add default headers to Flask's test client requests by overriding `FlaskClient.open`. When following redirects, the second request raises an error that an `EnvironBuilder` instance is being passed to `url_parse`.

### Expected Behavior

```python
from flask import Flask, redirect, url_for
from flask.testing import FlaskClient

app = Flask(__name__)

class CustomClient(FlaskClient):
    def open(self, *args, **kwargs):
        kwargs["headers"] = {"Extra-Key": "extra value"}
        return super().open(*args, **kwargs)

@app.route("/")
def home():
    return redirect(url_for("test"))

@app.route("/test")
def test():
    return "Hello, World!"

app.test_client_class = CustomClient
c = app.test_client()
rv = c.get("/", follow_redirects=True)
print(rv.data)
```

### Actual Behavior
```pytb
Traceback (most recent call last):
  File "/home/david/Projects/flask/example.py", line 21, in <module>
    rv = c.get("/", follow_redirects=True)
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/test.py", line 1029, in get
    return self.open(*args, **kw)
  File "/home/david/Projects/flask/example.py", line 9, in open
    return super().open(*args, **kwargs)
  File "/home/david/Projects/flask/src/flask/testing.py", line 222, in open
    return Client.open(
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/test.py", line 1016, in open
    environ, response = self.resolve_redirect(
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/test.py", line 948, in resolve_redirect
    return self.open(builder, as_tuple=True, buffered=buffered)
  File "/home/david/Projects/flask/example.py", line 9, in open
    return super().open(*args, **kwargs)
  File "/home/david/Projects/flask/src/flask/testing.py", line 215, in open
    builder = EnvironBuilder(self.application, *args, **kwargs)
  File "/home/david/Projects/flask/src/flask/testing.py", line 73, in __init__
    url = url_parse(path)
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/urls.py", line 457, in url_parse
    i = url.find(s(":"))
AttributeError: 'EnvironBuilder' object has no attribute 'find'
```
### Environment

* Python version: 3.6.9
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

### PR DESCRIPTION
**Pull request by Rohan-Salwan**
- Fixed  #3396

Checklist:

- [x] I did test that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [ ] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by Rohan-Salwan** [comment]
hi @davidism,
Actually i am trying to push some changes in PR but in checking it is showing error so can you guide me plz

**Comment by davidism** [comment]
You need to resolve merge conflicts, as the 2.0.x branch has been updated with other merged PRs since you opened this one. Including your own PR about CLI exceptions. Be sure to only include work for one issue in a branch.

**Comment by davidism** [comment]
Converting to draft until you fix finalize this PR, so that everyone doesn't keep getting notifications of each push.

**Comment by ThiefMaster** [comment]
Please read about how git rebases work. By making merges you are causing a rather big mess in your branch that's most likely rather hard to fix.

Alternative, copy the commit hashes of your relevant commit(s), then `git reset --hard upstream/2.0.x` and `git cherry-pick XXX` your commit hashes to get rid of all the unrelated mess.

**Comment by ThiefMaster** [comment]
Just FYI you do not need to close the PR to fix this - you can simply force-push after fixing things.

**Pull request closed without merging**
