### PR TITLE
Fix PEP8 issues and enforce PEP8 via pytest-pep8 (i.e. also during CI)

### PR DESCRIPTION
**Pull request by ThiefMaster**
E301 (no empty line before function/class) is disabled for files where having compact code (e.g. non-decorator based properties) makes sense.

### CODE REVIEW

**Comment by untitaker** [comment]
Interesting, why not flake8?

**Comment by ThiefMaster** [comment]
py.test integration (even though it probably could have been done via tox too)

**Comment by untitaker** [comment]
We should switch to one solution uniformly because otherwise contributors have
to follow different guidelines for different projects.

Atm Werkzeug uses flake8 in tox (with very weak settings)

**Comment by ThiefMaster** [comment]
ok i'll have a look and use flake8 here too

**Comment by ThiefMaster** [comment]
hm.. with flake8 there's no way of disabling certain checks per-file

**Comment by davidism** [comment]
I don't like the formatting where there is major indentation on all lines, everything gets very crowded at the right.  Instead, move the first argument to a new line as well and use normal wrapping rules.  The automatic wrapping detection in tools like PyCharm's formatter produces some weird lines, so manually verify that the lines actually look good.

~~~python
# from
permanent_session_lifetime = ConfigAttribute('PERMANENT_SESSION_LIFETIME',
                                             get_converter=_make_timedelta)
# to
permanent_session_lifetime = ConfigAttribute(
    'PERMANENT_SESSION_LIFETIME',
    get_converter=_make_timedelta
)
~~~

Also, can we disable the line length, or at least extend the it the modern guideline of 100 characters?  I've never been a fan of the 80 character hard limit, and it would alleviate the wrapping problem described above.

There are still some instances of `\` continuation.

**Comment by ThiefMaster** [comment]
If we go to >79 (which I'd highly appreciate, IMO the default limit results in less readable code), why not set 120 as a maximum for code and ~70 as a soft limit for comments/docstrings (they are more readable, but wrapping a long word because of 1 or 2 characters is pretty ugly)?

**Comment by davidism** [comment]
I'd rather have just one 120 character limit for everything.  But that might be a little to extreme.

**Comment by ThiefMaster** [comment]
@mitsuhiko what's your opinion on max-line-length=120 (or 100 in case you don't like 120)?

**Comment by jeffwidman** [comment]
It'd be great to see this merged. @mitsuhiko any input on max line length?

**Comment by untitaker** [comment]
I'm unsure if this is the proper way to enforce PEP-8 style. Maybe it should be gradually improved, to avoid massive merge conflicts between maintenance branches (and PRs)?

**Comment by JelteF** [comment]
Although Flake8 does not have native exclusion different filetypes it can be done using the flake8-putty extension:
https://github.com/jayvdb/flake8-putty

**Comment by davidism** [comment]
Closing this due to large number of merge conflicts. Unless we can close all other outstanding PRs first, I don't think a blanket change is the way to go, as it has a high potential of causing merge conflicts. Strategy I see going forward:

* Do some GitHub / git magic and figure out what files are not part of any open PR, and fix those.
* Add a tox test that filters flake8's output based on the lines git reports as changed and only fails if changed lines have lint issues. See [git-lint](https://github.com/sk-/git-lint/), for example, although it hasn't been updated recently and does not support flake8.

**Pull request closed without merging**
