### PR TITLE
Code fix for issue #1481

### PR DESCRIPTION
**Pull request by rawrgulmuffins**
This is a unit test and code fix for issue #1481 that keeps the previous behavior of get_root_path and intercepts the new `AttributeError` thrown by `pkgutil.get_loader`.

### CODE REVIEW

**Comment by untitaker** [comment]
Closing, see issue #1481 for rationale.

**Comment by untitaker** [comment]
We actually have https://github.com/mitsuhiko/flask/issues/1011, *another issue* open for this. I also elaborated there why I think that this fix isn't a good idea. I am still unsure about this.

**Comment by rawrgulmuffins** [comment]
Also, Sorry for double reporting. I didn't remember that I had seen this previously. =P

**Comment by jeffwidman** [comment]
Closing for now per https://github.com/pallets/flask/issues/1011#issuecomment-207290881

**Pull request closed without merging**
