### PR TITLE
changed / import to ( )

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Spaces inside `()` are awful. Please don't ever write `( foo )` in Python (or any other programming language). :)

Regardless of this, we do not accept style-related PRs.

**Comment by Abdur-rahmaanJ** [comment]
@ThiefMaster, it's a Js recommendation. thnx for info!

**Comment by ThiefMaster** [comment]
This is not JS, and common JS style guides such as prettier's ruleset, eslint defaults or the airbnb style guide do not use any spacing inside `(...)`, only inside `{ ... }`

**Comment by Abdur-rahmaanJ** [comment]
yes not rel to py. btw the () is John Resig's Jquery standard

**Comment by ThiefMaster** [comment]
...which is awful :)

**Pull request closed without merging**
