### PR TITLE
Inconsistent behaviour on request.get_json(cache=False) #2181 (solution)

### PR DESCRIPTION
**Pull request by sonuagarwal1008**
#2181 

```
#!/use/bin/env python
from flask import Flask, request
from flask import json
app = Flask(__name__)
@app.route('/', methods=["GET", "POST"])
def hello_uncached():
        if request.headers['Content-Type']=='application/json':
                json1 = json.dumps(request.json)
                data={"abc":"123"}
                json2 = json.dumps(data)
                return json1+'/'+json2
if __name__ == "__main__":
      app.run(host='0.0.0.0')
```
You can do it like this request.data will be used only when you are using text/plain in the case of json data use json.dumps(request.json).

`curl -H "Content-Type: application/json" -X POST http://127.0.0.1:5000 -d '{"foo":"bar"}'`

### CODE REVIEW

**Comment by untitaker** [comment]
That is merging a lot of code into the wrong branch.

**Comment by sonuagarwal1008** [comment]
cloud you please suggest what is the right branch to merge this code.

**Comment by ThiefMaster** [comment]
master or the latest maintenance branch (bugfixes usually go into maintenance for the current version). Rebase your branch to the branch you do the PR against. Note that you do not need to re-open the PR, you can change the target branch using the "edit" button on top.

**Comment by untitaker** [comment]
@ThiefMaster beat me to it. Note that simple `git rebase ...` won't suffice, you have to use `git rebase -i` to remove the commits that aren't part of your PR

**Comment by ThiefMaster** [comment]
Actually, your PR is from this repos's master - you need to open the PR with the branch containing your feature in your fork as the source.

**Comment by ThiefMaster** [comment]
It seems you never pushed your commit to your fork. Do that first. GitHub will even suggest you to open a PR once you did that when you go to https://github.com/pallets/flask/

**Pull request closed without merging**
