### PR TITLE
Add larger app ex

### PR DESCRIPTION
**Pull request by wgwz**
I chose the wrong base: https://github.com/pallets/flask/pull/2130

Original PR message:

> Addresses: #1902 (comment)
> 
> Confirms that the larger application as outlined in the docs, works as expected. For the sake of less confusion, for those working through this example, having src might be helpful. Not everyone will want to work along with the docs. If there are parts of the docs that are not clear, we should fix that as well. (They seemed clear to me).

Thiefmaster's response:

> The weird commits in this PR aside (rebase to upstream/master and force-push to fix), I'm not sure how useful this is to have in the repo... Especially since having a "large" app without an app factory is somewhat questionable...

My response:

> @ThiefMaster Sorry about that. I didn't choose correct base. I was thinking that in order to debug issues that people are having with code examples in the docs, it would be useful to have those examples on-hand.
> 
> I agree. But maybe until we can put something better together for #2027, this addition could just be temporary and we could deprecate this "larger applications" example at later time.

### CODE REVIEW

**Comment by untitaker** [comment]
This example doesn't work because it contains a circular import and precisely shows why you need app factories.

To separate views from the main app you should use blueprints.

**Comment by ThiefMaster** [comment]
I think it works since the `views` import is at the bottom, after `app` has been defined. Still a very good point though.

**Comment by untitaker** [comment]
Ah, I overread that this is from the docs, and yes, that actually works. I don't think we need to test this in any way though (I'd reserve `examples/` for more "complete" applications, not just patterns).

**Comment by wgwz** [comment]
I'm not by any means saying this is best practice. Just that having the hardcoded example accompanying the docs, might lead to less confusion for those reading it. (And a sanity check that what's in the docs works as it should.)

**Comment by untitaker** [comment]
Fair enough though this doesn't test anything. We should add a test stub as well that just imports and install the package in `tox.ini`.

**Comment by kblomqvist** [comment]
A week ago I got confused by circular imports when adding `models.py` to flaskr example that I was modifying to work as a large application. I think that the large app example should also showcase how to use models.

**Comment by untitaker** [comment]
Would like to see a rewrite of flaskr with flask-sqlalchemy

**Comment by wgwz** [comment]
While this PR isn't for flaskr and neither was [the comment](https://github.com/pallets/flask/issues/1902#issuecomment-269781735) that prompted me to work on this, I do agree. flaskr could be overhauled to show current best practices; i.e. app factories, blueprints, flask-sqlalchemy and the CLI, which also helps with #2027. Maybe at that point this whole larger app portion of the docs can be written with respect to flaskr. 

> Fair enough though this doesn't test anything because pytest doesn't import the package. We should add a test stub as well that just imports and install the package in tox.ini.

@untitaker assuming you want to go forward with this, would *tox.ini* change as below? and what else needs to change/be added? I don't follow what you are saying. (not familiar with tox.)

```
commands =
    # We need to install those after Flask is installed.
    pip install -e examples/flaskr
    pip install -e examples/minitwit
    pip install -e examples/patterns/largerapp
    py.test --cov=flask --cov-report html []
```

**Comment by untitaker** [comment]
@wgwz Yes exactly, it's just about installing the application in the virtualenv (otherwise you can't import it in the tests)

**Comment by wgwz** [comment]
@untitaker OK I understand now. Should I add some basic tests for it under `tests/test_apps`?

**Comment by untitaker** [comment]
The other example apps had their own testfolders iirc

On 31 December 2016 17:53:14 CET, Kyle Lawlor <notifications@github.com> wrote:
>@untitaker OK I understand now. Should I add some basic tests for it
>under `tests/test_apps`? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/pull/2131#issuecomment-269873161

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wgwz** [comment]
should this be closed?

**Comment by untitaker** [comment]
I think it's fine as is, thanks :)

**Pull request merged**
