### PR TITLE
wtforms: Add missing closing tags

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I'm all for closing the `<dt>` tag (seems super ugly not to do so), but not so much of the XML-ish `/` on a content-less element.

**Comment by ThiefMaster** [comment]
I'd rather remove the action  attribute from the `<form>` tag altogether; when submitting the form to the same page there's no need/reason to specify it.

**Comment by bfontaine** [comment]
@ThiefMaster Fixed.

**Comment by mitsuhiko** [comment]
Why :(

**Comment by mitsuhiko** [comment]
What's wrong with leaving them open? Looks so much nicer.

**Comment by davidism** [comment]
I always get tripped up trying to remember if a given tag requires the closing tag, or whether I just closed the previous tag unintentionally.  So it's practical vs aesthetic, implicit vs explicit.  @mitsuhiko If you like them that way, I'm fine with a policy of no optional closing tags.

**Comment by mitsuhiko** [comment]
I don't understand what the reason to close them is because if you consider how the parser works, the tag does not do anything. You cannot keep a tag open if you put an illegal tag in. Eg: `<p>foo<p>bar</p>baz</p>` is just unlogical markup. It automatically becomes `<p>foo<p>bar<p>baz`.

**Comment by davidism** [comment]
Yeah, fair enough, the parser's going to give the same result either way.

**Comment by bfontaine** [comment]
This is documentation; the primary targets are developpers, not HTML parsers 😃 
I personally do find reading HTML code disturbing if tags are not properly closed. I guess it’s like semicolons in JS: it works until it breaks because you forgot an edge-case:

```html
<!-- this works as expected -->
<p>Foo
<p>Bar

<!-- this doesn’t -->
<div>Foo
<div>Bar
```

Also old browsers might not handle well tags that aren’t properly closed. It’s something that doesn’t cost a lot of time and ensures your page is correctly displayed in any browser. I can’t find any list of best practices for autoring HTML that doesn’t list a variant of “Close your tags” ([1](http://code.tutsplus.com/tutorials/30-html-best-practices-for-beginners--net-4957), [2](http://sixrevisions.com/web-standards/20-html-best-practices-you-should-follow/), [3](https://github.com/hail2u/html-best-practices), [4](https://isobar-idev.github.io/code-standards/), [5](http://learn.shayhowe.com/html-css/writing-your-best-code/), [6](http://www.w3schools.com/html/html5_syntax.asp), [7](http://www.codeproject.com/Tips/666578/HTML5-and-Some-CSS-Best-Practice)).

**Pull request merged**
