### PR TITLE
Replace `http://` with `https://` in cherokee links in docs/deploying

### LINKED ISSUE #4245: Links in docs/deploying: cherokee-project.com supports tls connection with CloudFlare certificates
Links to Cherokee in docs/deploying/{fastcgi.rst,uwsgi.rst} are written as `http://` instead of `https://`. However, cherokee-project.com supports tls connection with CloudFlare certificates.

Therefore, it would be a little better to replace `http://` with `https://`.

Environment:

- Python version: -
- Flask version: -

https://cherokee-project.com/

Screenshot_2021-08-28_12-08-05

Screenshot_2021-08-28_12-08-11

### PR DESCRIPTION
**Pull request by nabbisen**
Replace `http://` with `https://` in cherokee links in docs/deploying.

- fixes #4245

### CODE REVIEW

**Comment by davidism** [comment]
Please rebase to the 2.0.x branch.

**Comment by nabbisen** [comment]
@davidism 
Thank you for your reviewing. I edited this PR to change its base to 2.0.x. Did I get what you meant?

**Comment by davidism** [comment]
You need to rebase and force push as well

**Comment by nabbisen** [comment]
@davidism
Thank you. Sorry but I didn't find how to modify this existing PR with git-rebase. I will recreate PR.

**Comment by greyli** [comment]
You can change the base branch to 2.0.x with the following commands:

```
git rebase --onto origin/2.0.x origin/main
git push -f
```

（By the way, change the commit message to something like "Update cherokee links in docs/deploying" will be more descriptive.）

**Comment by nabbisen** [comment]
@greyli 
Thank you for your detailed commands. I have perhaps done it!

**Comment by greyli** [comment]
Not yet. When you did it, this PR will only contain one commit. Try to find more details about changing the base branch [here](https://stackoverflow.com/questions/10853935/change-branch-base).

I tried to force push this on my computer but failed. Did you enable the "Allow edits and access to secrets by maintainers" option on the bottom of the right sidebar on this page?

**Comment by nabbisen** [comment]
Hmm.. thank you and so sorry for your time. I think it's good to recreate PR after all...

> Not yet. When you did it, this PR will only contain one commit. Try to find more details about changing the base branch [here](https://stackoverflow.com/questions/10853935/change-branch-base).

I made one commit with two files.

> I tried to force push this on my computer but failed. Did you enable the "Allow edits and access to secrets by maintainers" option on the bottom of the right sidebar on this page?

Yes, off course.

**Comment by nabbisen** [comment]
Recreated as #4249 .

**Pull request closed without merging**
