### PR TITLE
add models 

### PR DESCRIPTION
**Pull request by AlaaProg**
add file models 
             Inside: 
                       # : Controllers.py 
                       # : methods.py 
& add class Cookies in helpers.py

you can watch all Updates in this video 
[](https://www.youtube.com/watch?v=-E6f6JzlYVA)

### CODE REVIEW

**Comment by ThiefMaster** [comment]
WTH is this?!

**Comment by AlaaProg** [comment]
nothing -_-

**Comment by AlaaProg** [comment]
😐why

2018-01-17 11:34 GMT+03:00 Adrian <notifications@github.com>:

**Comment by ThiefMaster** [comment]
1) this code does not belong into flask
2) this code is garbage

**Comment by AlaaProg** [comment]
okeY !! this code is garbage
Thinks

2018-01-17 15:10 GMT+03:00 Adrian <notifications@github.com>:

**Pull request closed without merging**
