### PR TITLE
FIX py.test import error

### PR DESCRIPTION
**Pull request by netspyer**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
The `tests` folder shouldn't be a package. What's the problem you are trying to solve?

**Comment by RonnyPfannschmidt** [comment]
@netspyer its very typical that the tests folder does NOT have a __init__.py in order to avoid a multitude of python-path issues

**Comment by netspyer** [comment]
When I run `make test` under the repo folder `flask`.
None of tests was run!
I checked __Makefile__, found test was run by `pytest`.
But, it still not working with `pytest tests`.
while put an `__init__.py` into tests, then run it again, testing is start normally.

**Comment by netspyer** [comment]
by the way, my pytest version is __3.0.3__

**Comment by davidism** [comment]
cc @wgwz This is related to flaskr and minitwit changes.

This is not the correct fix.  `pytest tests` works fine for me.

**Comment by netspyer** [comment]
@davidism It reports `cannot import name get_version`

**Comment by davidism** [comment]
I can't reproduce your issue.  If you are getting an error, you should open a bug report with a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of the issue you're having.  Such as the environment, command, and traceback.

**Comment by untitaker** [comment]
The `make release` target is indeed broken due to the updates to the examples, but I don't get the error message OP describes.

**Comment by netspyer** [comment]
@davidism 

**Environment**: 

- macOS 10.12.1 
- Python 2.7.12
- pytest-3.0.3
- Flask repo: latest(commit: _ec9717502f36126b8a371b73a5730b2092948ca2_)

**Run**:

     $  cd /Users/me/gits/flask
     $  pytest tests


**Output**:
>   ___________ ERROR collecting tests/test_cli.py ___________________________
> ImportError while importing test module '/Users/me/gits/flask/tests/test_cli.py'.
> Original error message:
>    'cannot import name get_version'
> Make sure your test modules/packages have valid Python names.
> !!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by untitaker** [comment]
I can reproduce the issue

**Comment by untitaker** [comment]
How have you installed Flask? `pip install -e .` or something else?

**Comment by netspyer** [comment]
Now, it's ok.

@untitaker yes! I installed an old Flask, uninstall it fix my issue.
Must the tests run after flask installed?
or else tests report could not find module `flask`.
Is this normal?

**Comment by untitaker** [comment]
Yeah it's normal. Some tests rely on Flask being properly installed.

**Comment by untitaker** [comment]
BTW I pushed a commit that changes `make test` to use tox.

**Pull request closed without merging**
