### PR TITLE
Update CHANGES.rst

### PR DESCRIPTION
**Pull request by CatarinaPBressan**
Fix the issue link in the Flask 3.0.1 Changelog in the send_file argument type entry

### CODE REVIEW

**Comment by davidism** [comment]
Please target docs changes to the maintenance branch (3.0.x) so that they show up in those docs builds.

**Comment by CatarinaPBressan** [comment]
Ok, done.

**Comment by davidism** [comment]
You need to rebase to change the target, not only change it in the GitHub UI.

**Comment by CatarinaPBressan** [comment]
I tried rebase but it was a mess (I didnt see your edit with the commands) so I created a new PR. https://github.com/pallets/flask/pull/5618 Sorry for the confusion.

**Pull request closed without merging**
