### PR TITLE
isolate templates between blueprints

### PR DESCRIPTION
**Pull request by teddy-hoo**
see the test

### CODE REVIEW

**Comment by ThiefMaster** [comment]
This is a breaking change and in many cases not what you want, e.g. if you merely use blueprints to structure your application.

**Comment by ThiefMaster** [comment]
If you need this in your application, override the jinja loader.

**Comment by teddy-hoo** [comment]
Do you mean flask should not support this feature?  or my code should consider more cases?
Thx a lot!

**Comment by ThiefMaster** [comment]
the former - it's something better done inside your application

**Comment by teddy-hoo** [comment]
I can not understand.
I use blueprint as component of my app, but one blueprint can use templates in other blueprints. Why not  the components be independent?

**Comment by ThiefMaster** [comment]
Because that's only one way to use blueprints. For example, your blueprint most likely wants to use templates from your app (like your base layout template) and depending on how you structure things some components require another component and also use some of that component's templates.

**Comment by davidism** [comment]
#1537

**Pull request closed without merging**
