### PR TITLE
Addressing Issue 1809

### PR DESCRIPTION
**Pull request by Sanjurjo7**
Added to docstring for Flask.register_blueprint to clarify kwargs.  Was unsure of the conventions for using :ref: but figured this fit, please let me know if there's a better way to do that.

### CODE REVIEW

**Comment by jeffwidman** [comment]
You should review PEP 257, as there are a couple of docstring conventions you're missing.

**Comment by Sanjurjo7** [comment]
Got it. Thanks for the reference, will give it an update this evening.

Sent from my Fire

**Comment by Sanjurjo7** [comment]
Done.
```
"""Registers a blueprint on the application. For information about 
blueprints head over to :ref: 'blueprints'.

Blueprint name is passed in as first argument	
Options are passed as additional keyword arguments and forwarded to 
blueprints in the 'options' dict.
options include:
	subdomain, url_prefix, url_defaults, 
	static_folder, static_url_path,	
	template_folder, root_path
All options set to None by default, (i.e. static_folder=None, 
root_path=None, etc) and are handled by blueprints.py 
Keyword arguments:
subdomain -- sets a subdomain for the blueprint
url_prefix -- sets the prefix for all URLs defined on the blueprint.
	(url_prefix='/<lang code>')
       url_defaults -- a dictionary with URL default that is added to each 
		and every URL defined with this blueprint 
		(url_defalts={'endpoint':'value'})
static_folder -- adds a static folder to urls for this blueprint
static_url_path -- adds static url path to urls in this blueprint
template_folder -- sets an alternate template folder for pages from
		this blueprint
		defaults to app template folder
root_path -- sets an alternate root path for pages from this blueprint
	defaults to app root path

.. versionadded:: 0.7
"""
```

**Comment by ThiefMaster** [comment]
The first word should be "Register" (command-style)

> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".

**Comment by davidism** [comment]
I appreciate the effort, but this doesn't read at all like the other docs.  It has multiple grammar issues.  It's not formatted correctly.  Please review other documentation examples.

**Comment by Sanjurjo7** [comment]
I left the first line as it was already in the docs, easy enough to change.

@davidism, Which grammar issues? and do you have a paragon documentation example in mind? I was trying not to repeat all the instructions from the blueprints, perhaps I put too little?

**Comment by Sanjurjo7** [comment]
I'm replacing the references to the kwargs with :param kwarg: is that the bit you mean should be set apart with double backticks @ThiefMaster?

**Comment by Sanjurjo7** [comment]
```
        """Register a blueprint on the application. For information about 
        blueprints head over to :ref: `blueprints`.

        The blueprint name is passed in as the first argument.	
        Options are passed as additional keyword arguments and forwarded to 
        `blueprints` in an "options" dictionary.

        :param subdomain: set a subdomain for the blueprint
        :param url_prefix: set the prefix for all URLs defined on the blueprint.
        ``(url_prefix='/<lang code>')``
        :param url_defaults: a dictionary with URL defaults that is added to 
            each and every URL defined with this blueprint
        :param static_folder: add a static folder to urls in this blueprint
        :param static_url_path: add a static url path to urls in this blueprint
        :param template_folder: set an alternate template folder
        :param root_path: set an alternate root path for this blueprint

	.. versionadded:: 0.7
        """
```

How's that. Read up on reST in Sphinx, but I'm not sure how to run Sphinx locally, honestly.

**Comment by ThiefMaster** [comment]
You just install it using pip and then use the Makefile in the `docs` folder to build the HTML docs by running `make html`

**Comment by Sanjurjo7** [comment]
Okay, this format is much better, but I need to know how to get that line with the reference to the blueprints page set up correctly. What did I do wrong there?

**Comment by davidism** [comment]
I'm going to merge this, then move it over to the documentation for `Blueprint`, and clean up a few other things.  Thanks for the initiative.

**Comment by Sanjurjo7** [comment]
It was a good learning experience for me, thanks for all the feedback!

**Comment by geusebi** [comment]
Maybe that's a stupid question but, do ``register_blueprint'' actually handle ``root_path'', ``template_folder'' and so on? Also why the first argument is the name of the blueprint? Shouldn't it be the actual blueprint?
This docstring looks more like a good docstring for the ``Blueprint'' constructor.
Feel free to ignore this post if I'm wrong :)
GE

**Comment by untitaker** [comment]
This PR seems to be completely incorrect as `blueprint.name` is accessed further below.

**Comment by untitaker** [comment]
@davidism Could you take a look at this again?

**Pull request merged**
