### PR TITLE
Update minitwit & improve testing for examples

### PR DESCRIPTION
**Pull request by wgwz**
* Related to #1945
* Re-works minitwit to be installed and run as:

    pip install --editable .
    export FLASK_APP=minitwit.minitwit
    export FLASK_DEBUG=1
    flask initdb
    flask run

* added flaskr and minitwit to norecursedirs
  * tests not properly run when using pytest standards
  * see: http://stackoverflow.com/questions/38313171/configuring-pytest-with-installable-examples-in-a-project
* Both flaskr and minitwit now follow pytest standards.
* Tests can for them as `py.test` or `python setup.py test`

### CODE REVIEW

**Comment by wgwz** [comment]
I chose the wrong base. Re-filed on the 0.11-maintenance branch.

**Comment by jeffwidman** [comment]
In general, we commit against master and if needed a maintainer will backport to a maintenance branch. That way we avoid diverging from master as much as possible.

**Comment by davidism** [comment]
@jeffwidman no, way easier to commit against what's actually being fixed, then merge the result forward.

**Comment by jeffwidman** [comment]
Hmm, doesn't the problem exist in both master and maintenance branch? 

On the other projects I'm involved with when that's the case we always do the PR against master and then cherrypick as needed to the relevant maintenance branch. I'm fine with either flow, but not understanding the rationale here.

**Pull request closed without merging**
